### ISSUE TITLE
same person here and update to new version error

### ISSUE THREAD

**Issue by schxar** [TREE-Ind/Blender-GPT#3]
Traceback (most recent call last):
  File "C:\Users\schxa\Downloads\blender-3.4.1-windows-x64\blender-3.4.1-windows-x64\3.4\python\lib\site-packages\numpy\core\__init__.py", line 23, in <module>
    from . import multiarray
  File "C:\Users\schxa\Downloads\blender-3.4.1-windows-x64\blender-3.4.1-windows-x64\3.4\python\lib\site-packages\numpy\core\multiarray.py", line 16, in <module>
    from ._multiarray_umath import (
ImportError: cannot import name 'fastCopyAndTranspose' from 'numpy.core._multiarray_umath' (C:\Users\schxa\Downloads\blender-3.4.1-windows-x64\blender-3.4.1-windows-x64\3.4\python\lib\site-packages\numpy\core\_multiarray_umath.cp310-win_amd64.pyd)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\schxa\Downloads\blender-3.4.1-windows-x64\blender-3.4.1-windows-x64\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\schxa\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-GPT-main\__init__.py", line 12, in <module>
    from . import ui, operators, dependencies
  File "C:\Users\schxa\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-GPT-main\operators.py", line 2, in <module>
    from . import gpt4, whisper
  File "C:\Users\schxa\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-GPT-main\whisper.py", line 2, in <module>
    import numpy as np
  File "C:\Users\schxa\Downloads\blender-3.4.1-windows-x64\blender-3.4.1-windows-x64\3.4\python\lib\site-packages\numpy\__init__.py", line 141, in <module>
    from . import core
  File "C:\Users\schxa\Downloads\blender-3.4.1-windows-x64\blender-3.4.1-windows-x64\3.4\python\lib\site-packages\numpy\core\__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "C:\Users\schxa\Downloads\blender-3.4.1-windows-x64\blender-3.4.1-windows-x64\3.4\python\bin\python.exe"
  * The NumPy version is: "1.24.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: cannot import name 'fastCopyAndTranspose' from 'numpy.core._multiarray_umath' (C:\Users\schxa\Downloads\blender-3.4.1-windows-x64\blender-3.4.1-windows-x64\3.4\python\lib\site-packages\numpy\core\_multiarray_umath.cp310-win_amd64.pyd)

**Comment by schxar** [comment]
nothing， just a numpy error and fix in 30 sec
