### ISSUE TITLE
What is the reason for this error?

### ISSUE THREAD

**Issue by sunzhen11** [TREE-Ind/Blender-GPT#6]
Traceback (most recent call last):
  File "D:\Soft\Blender3.4.1\3.4\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Administrator.DESKTOP-GO7IVG7\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-GPT-main\__init__.py", line 12, in <module>
    from . import ui, operators, dependencies
  File "C:\Users\Administrator.DESKTOP-GO7IVG7\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-GPT-main\operators.py", line 2, in <module>
    from . import gpt4, whisper
  File "C:\Users\Administrator.DESKTOP-GO7IVG7\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\Blender-GPT-main\gpt4.py", line 1, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

![image](https://user-images.githubusercontent.com/53415999/228120067-c560c8f3-3a96-4612-b143-e1587c8eb19a.png)

**Comment by moebis** [comment]
Same problem here too. On Apple Silicon Mac.

**Comment by Esimacio** [comment]
I can join the mass, same problem here too, Blender 3.4

**Comment by TREE-Ind** [comment]
Looks like the script to install python modules is where this issue lies.  We're going to go ahead and bundle the modules with the add-on which should fix this issue.

Update should be pushed today sometime.

**Comment by TREE-Ind** [comment]
This error should now be fixed in the latest update, we've bundled all necessary dependencies with the add-on which should resolve this problem.  Closing for now, but please re-open if you still have trouble installing.  Cheers.

**Comment by moebis** [comment]
@TREE-Ind still fails:

[https://imgur.com/C4u0cJs](https://imgur.com/C4u0cJs)

**Comment by Ruka1998** [comment]
> @TREE-Ind still fails:
> 
> https://imgur.com/C4u0cJs

Same

**Comment by TREE-Ind** [comment]
Added a couple of python modules that somehow didn't make the last push, hopefully will work now.

**Comment by moebis** [comment]
@TREE-Ind it still fails. I might just give up on this. It looked promising, but 3 versions and the same error doesn't instill confidence. Sorry.
