### ISSUE TITLE
ModuleNotFoundError: No module named 'openai'

### ISSUE THREAD

**Issue by 4minus1d** [TREE-Ind/Blender-GPT#7]
I get this error when trying to enable the addon in preferences, don't know if this is something I'm doing wrong or if its just a bug..

Error Log:

Traceback (most recent call last):
  File "C:\Users\Zohaib\Desktop\3.5 Alpha 14 Feb\blender-3.5.0-alpha+main.46c34ba1f666-windows.amd64-release\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Zohaib\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Blender-GPT-main\__init__.py", line 12, in <module>
    from . import ui, operators, dependencies
  File "C:\Users\Zohaib\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Blender-GPT-main\operators.py", line 2, in <module>
    from . import gpt4, whisper
  File "C:\Users\Zohaib\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\Blender-GPT-main\gpt4.py", line 1, in <module>
    import openai
ModuleNotFoundError: No module named 'openai'

**Blender: version: 3.5.0 Alpha
Build date: 2023-02-14, 04:50:07
Platform: 'Windows-10-10.0.19045-SP0'**

**Comment by TREE-Ind** [comment]
Latest push should fix this, we've bundles all necessary dependencies with the add-on which should resolve this problem.  Closing for now, but please re-open if you still have trouble installing.  Cheers.
